import seoHeroImage from "./images/seo1.png";
import seoWorkflowImage from "./images/seo2.png";
import seoStatsImage from "./images/seo3.png";
import brandHeroImage from "./images/brand1.png";
import brandWorkflowImage from "./images/brand2.jpg";
import brandExpertiseImage from "./images/brand3.jpg";
import ebayHeroImage from "./images/ebay1.png";
import ebayWorkflowImage from "./images/ebay2.jpg";
import ebayExpertiseImage from "./images/ebay3.jpg";
import socialHeroImage from "./images/social1.png";

export const seoSemContent = {
    accent: "#FF776F",
    category: "Marketing Services",
    hero: { title: "SEO/SEM", subtitle: "Search visibility & paid campaigns.", description: "Optimizing your digital presence to rank higher in search results and managing paid campaigns for maximum ROI. We drive qualified traffic that converts.", image: seoHeroImage },
    stats: { items: [{ value: "200+", label: "Sites Optimized" }, { value: "3x", label: "Avg. Traffic Lift" }, { value: "2.5", label: "ROAS Average" }, { value: "90", suffix: "days", label: "SEO Results" }], image: seoStatsImage },
    workflow: { label: "SEO/SEM Workflow", title: "We Grow Search Traffic", description: "From audit to optimization — organic and paid search that delivers.", steps: [{ step: "01", label: "Audit" }, { step: "02", label: "Optimize" }, { step: "03", label: "Scale" }], image: seoWorkflowImage },
    happyClients: { label: "Trusted by marketers", title: "Happy Clients", stat: "200+", subtext: "sites and campaigns managed", tags: ["Local SEO", "E‑commerce", "SaaS", "B2B", "Google Ads", "Bing", "Programmatic", "Retargeting"] },
    intelligentSection: { title: "SEO & SEM Excellence.", description: "At NerdX Solutions, we combine organic SEO with paid search for maximum visibility. Technical SEO, content strategy, and PPC management — we drive qualified traffic that converts.", bullets: ["Technical SEO: Site speed, structure, schema, and crawlability.", "Content Strategy: Keyword research, on-page optimization, and content creation.", "Link Building: Quality backlinks that boost authority.", "PPC Management: Google Ads, Bing, and programmatic — optimized for ROAS.", "Analytics & Reporting: Clear metrics and actionable insights."] },
    challengeSolution: { challenge: "Low visibility in search means missed opportunities. Poorly managed paid campaigns burn budget without ROI.", solution: "NerdX optimizes your search presence — organic and paid. We drive qualified traffic, improve rankings, and maximize return on ad spend.", tags: ["Data-Driven", "Full-Funnel", "ROI Focused"] },
    testimonial: { quote: "Search is intent — people are telling you what they want. We help you show up when it matters.", attribution: "NerdX Search Philosophy", ctaText: "Book a free SEO/SEM audit and let's grow your search visibility." },
    principles: { title: "Why Search Matters", subtitle: "Three pillars of search marketing", items: [{ title: "Intent Alignment", desc: "Match your content and ads to what users are searching for.", emoji: "◇" }, { title: "Technical Foundation", desc: "Fast sites, clean structure, and crawlable content.", emoji: "◆" }, { title: "Data-Driven", desc: "Every decision backed by analytics and testing.", emoji: "○" }] },
    expertise: { title: "Our SEO/SEM Expertise", subtitle: "Organic search and paid campaigns.", cards: [{ icon: "◇", title: "Technical SEO", text: "Site audits, speed optimization, and technical fixes." }, { icon: "◆", title: "Content SEO", text: "Keyword strategy, on-page optimization, content creation." }, { icon: "○", title: "PPC Management", text: "Google Ads, Bing, and programmatic campaigns." }, { icon: "●", title: "Analytics", text: "Tracking, reporting, and optimization recommendations." }] },
    techStack: { subtitle: "SEO & PPC tools", items: ["Google Analytics", "Search Console", "SEMrush", "Ahrefs", "Google Ads"], extra: "Schema · GTM · Attribution" },
    processSteps: { subtitle: "From audit to scale", items: [{ num: "01", title: "Audit & Strategy", text: "We analyze your site, competitors, and opportunities. A clear roadmap before we execute.", link: "Know More" }, { num: "02", title: "Optimization", text: "Technical fixes, content optimization, and campaign setup.", link: "Know More" }, { num: "03", title: "Execution & Iterate", text: "Ongoing optimization based on performance data.", link: "Know More" }, { num: "04", title: "Scale & Report", text: "Scale what works. Clear reporting and actionable insights.", link: "Know More" }] }
};

export const brandingStrategicsContent = {
    accent: "#FF776F",
    category: "Marketing Services",
    hero: { title: "Branding Strategics", subtitle: "Market position & messaging.", description: "Defining your market position and messaging to create a long-term competitive advantage for your business. Strategy that drives growth.", image: brandHeroImage },
    stats: { items: [{ value: "150+", label: "Strategies Delivered" }, { value: "40", suffix: "%", label: "Revenue Impact" }, { value: "5x", label: "Brand Recall" }, { value: "4", suffix: "wk", label: "Strategy Sprint" }], image: null },
    workflow: { label: "Strategy Workflow", title: "We Define Brand Strategy", description: "From research to roadmap — positioning that wins.", steps: [{ step: "01", label: "Research" }, { step: "02", label: "Define" }, { step: "03", label: "Execute" }], image: brandWorkflowImage },
    happyClients: { label: "Trusted by growth teams", title: "Happy Clients", stat: "150+", subtext: "brand strategies delivered", tags: ["B2B", "B2C", "Startups", "Enterprise", "Rebrands", "Product Launch", "Positioning", "Messaging"] },
    intelligentSection: { title: "Branding Strategy Expertise.", description: "At NerdX Solutions, we help you define who you are, who you serve, and how you win. Market positioning, messaging frameworks, and competitive strategy — the foundation for sustainable growth.", bullets: ["Market Research: Audience, competitors, and market dynamics.", "Positioning: Your unique place in the market and why it matters.", "Messaging Framework: Value props, key messages, and proof points.", "Competitive Strategy: How to differentiate and win.", "Go-to-Market: Strategy for launch and growth."] },
    challengeSolution: { challenge: "Vague positioning and inconsistent messaging confuse customers. Without a clear strategy, marketing efforts fall flat.", solution: "NerdX defines your positioning and messaging with clarity. A strategy that guides every touchpoint and drives long-term competitive advantage.", tags: ["Clear Positioning", "Data-Backed", "Actionable"] },
    testimonial: { quote: "Strategy isn't a document — it's the logic that makes every decision easier. We build that logic.", attribution: "NerdX Strategy Philosophy", ctaText: "Book a free strategy session and let's define your competitive advantage." },
    principles: { title: "Why Strategy Matters", subtitle: "Three principles of effective branding strategy", items: [{ title: "Clarity Wins", desc: "When you know who you are, customers do too.", emoji: "◇" }, { title: "Differentiation", desc: "Stand out or get lost. We find your edge.", emoji: "◆" }, { title: "Consistency", desc: "One message, everywhere. Strategy enables it.", emoji: "○" }] },
    expertise: { title: "Our Strategy Expertise", subtitle: "Positioning and messaging that drives growth.", image: brandExpertiseImage, cards: [{ icon: "◇", title: "Market Research", text: "Audience, competitor, and market analysis." }, { icon: "◆", title: "Positioning", text: "Unique value proposition and market place." }, { icon: "○", title: "Messaging", text: "Key messages, proof points, and storytelling." }, { icon: "●", title: "GTM Strategy", text: "Launch and growth strategy." }] },
    techStack: { subtitle: "Strategy tools", items: ["Miro", "Notion", "Surveys", "Interviews", "Competitive Analysis"], extra: "Personas · Journeys · Workshops" },
    processSteps: { subtitle: "From research to roadmap", items: [{ num: "01", title: "Discovery & Research", text: "Stakeholder interviews, market research, and competitive analysis.", link: "Know More" }, { num: "02", title: "Strategy Development", text: "Positioning, messaging framework, and strategic recommendations.", link: "Know More" }, { num: "03", title: "Validation", text: "Test messaging with audiences. Refine based on feedback.", link: "Know More" }, { num: "04", title: "Handoff & Activation", text: "Strategy document, workshops, and activation support.", link: "Know More" }] }
};

export const socialMediaContent = {
    accent: "#FF776F",
    category: "Marketing Services",
    hero: { title: "Social Media Marketing", subtitle: "Community & content that builds brands.", description: "Managing community engagement and content distribution across platforms to build brand loyalty and awareness. We help you connect and convert.", image: socialHeroImage },
    stats: { items: [{ value: "100+", label: "Accounts Managed" }, { value: "2x", label: "Engagement Lift" }, { value: "50K+", label: "Community Growth" }, { value: "Daily", label: "Content Cadence" }], image: socialHeroImage },
    workflow: { label: "Social Workflow", title: "We Manage Social Presence", description: "From strategy to daily posting — social that builds community.", steps: [{ step: "01", label: "Strategy" }, { step: "02", label: "Create" }, { step: "03", label: "Engage" }], image: socialHeroImage },
    happyClients: { label: "Trusted by brands", title: "Happy Clients", stat: "100+", subtext: "social accounts managed", tags: ["Instagram", "LinkedIn", "Twitter", "Facebook", "TikTok", "YouTube", "Pinterest", "Community"] },
    intelligentSection: { title: "Social Media Marketing Expertise.", description: "At NerdX Solutions, we build social presence that matters. Content strategy, community management, and paid social — we help you connect with your audience and grow your brand.", bullets: ["Content Strategy: What to post, when, and why. Data-driven calendar.", "Community Management: Engage, respond, and build relationships.", "Paid Social: Meta, LinkedIn, TikTok — campaigns that convert.", "Analytics: Track engagement, reach, and ROI.", "Influencer & UGC: Partnerships and user-generated content."] },
    challengeSolution: { challenge: "Inconsistent posting and generic content get ignored. Without strategy, social feels like noise.", solution: "NerdX manages your social presence with purpose. Strategic content, community engagement, and paid amplification — we build presence that converts.", tags: ["Strategy-Led", "Community-First", "Data-Driven"] },
    testimonial: { quote: "Social isn't about followers — it's about connection. We help you build real community.", attribution: "NerdX Social Philosophy", ctaText: "Book a free social audit and let's grow your community." },
    principles: { title: "Why Social Matters", subtitle: "Three pillars of social success", items: [{ title: "Authentic Voice", desc: "Content that sounds like you, not a corporation.", emoji: "◇" }, { title: "Consistent Presence", desc: "Regular posting builds habit and trust.", emoji: "◆" }, { title: "Community Over Reach", desc: "Engaged followers beat vanity metrics.", emoji: "○" }] },
    expertise: { title: "Our Social Expertise", subtitle: "Strategy, content, and community management.", cards: [{ icon: "◇", title: "Content Strategy", text: "Calendar, themes, and platform-specific approach." }, { icon: "◆", title: "Community Mgmt", text: "Engagement, DMs, and relationship building." }, { icon: "○", title: "Paid Social", text: "Meta, LinkedIn, TikTok ads and retargeting." }, { icon: "●", title: "Analytics", text: "Performance tracking and optimization." }] },
    techStack: { subtitle: "Social tools", items: ["Meta Business", "LinkedIn", "Buffer", "Canva", "Sprout"], extra: "Scheduling · Analytics · Listening" },
    processSteps: { subtitle: "From strategy to daily execution", items: [{ num: "01", title: "Audit & Strategy", text: "We analyze your presence, audience, and competitors. A clear content strategy.", link: "Know More" }, { num: "02", title: "Content & Calendar", text: "Content pillars, calendar, and creative production.", link: "Know More" }, { num: "03", title: "Publish & Engage", text: "Consistent posting and community engagement.", link: "Know More" }, { num: "04", title: "Optimize & Scale", text: "Data-driven optimization and paid amplification.", link: "Know More" }] }
};

export const ebayStoreContent = {
    accent: "#FF776F",
    category: "Marketing Services",
    hero: { title: "EBay Store Setup & Management", subtitle: "Optimized storefronts for sales.", description: "Setting up and optimizing eCommerce storefronts for improved sales performance. We help you list, optimize, and scale your eBay presence.", image: ebayHeroImage },
    stats: { items: [{ value: "75+", label: "Stores Managed" }, { value: "40", suffix: "%", label: "Sales Lift" }, { value: "500+", label: "Listings Optimized" }, { value: "Ongoing", label: "Management" }], image: null },
    workflow: { label: "Store Workflow", title: "We Set Up & Manage eBay Stores", description: "From setup to ongoing optimization — stores that sell.", steps: [{ step: "01", label: "Setup" }, { step: "02", label: "Optimize" }, { step: "03", label: "Scale" }], image: ebayWorkflowImage },
    happyClients: { label: "Trusted by sellers", title: "Happy Clients", stat: "75+", subtext: "eBay stores optimized", tags: ["Retail", "Wholesale", "Dropship", "Vintage", "Collectibles", "Electronics", "Fashion", "Automotive"] },
    intelligentSection: { title: "eBay Store Expertise.", description: "At NerdX Solutions, we help sellers maximize eBay performance. Store setup, listing optimization, photography, and ongoing management — we turn your inventory into sales.", bullets: ["Store Setup: Professional storefronts with branding and categories.", "Listing Optimization: Titles, descriptions, keywords for visibility.", "Photography & Media: Product images that convert.", "Pricing Strategy: Competitive pricing and promotions.", "Ongoing Management: Listings, analytics, and optimization."] },
    challengeSolution: { challenge: "Poor listings and generic storefronts get buried. Without optimization, you're leaving sales on the table.", solution: "NerdX optimizes your eBay presence. Professional setup, optimized listings, and ongoing management — we help you sell more.", tags: ["Optimized Listings", "Professional Store", "Ongoing Support"] },
    testimonial: { quote: "eBay rewards sellers who invest in their presence. We help you stand out and sell.", attribution: "NerdX eCommerce Philosophy", ctaText: "Book a free eBay audit and let's grow your store." },
    principles: { title: "Why eBay Optimization", subtitle: "Three drivers of eBay success", items: [{ title: "Visibility", desc: "Optimized listings rank higher and get more views.", emoji: "◇" }, { title: "Trust", desc: "Professional storefronts build buyer confidence.", emoji: "◆" }, { title: "Consistency", desc: "Regular listings and management keep momentum.", emoji: "○" }] },
    expertise: { title: "Our eBay Expertise", subtitle: "Setup, optimization, and management.", image: ebayExpertiseImage, cards: [{ icon: "◇", title: "Store Setup", text: "Branding, categories, and professional storefront." }, { icon: "◆", title: "Listing Optimize", text: "Titles, keywords, descriptions for visibility." }, { icon: "○", title: "Media & Photos", text: "Product photography and listing media." }, { icon: "●", title: "Ongoing Mgmt", text: "Listings, analytics, and optimization." }] },
    techStack: { subtitle: "eBay tools", items: ["eBay Seller Hub", "Terapeak", "Listing Software", "Analytics"], extra: "Bulk Listing · Promotions · Inventory" },
    processSteps: { subtitle: "From setup to scale", items: [{ num: "01", title: "Audit & Setup", text: "We review your current presence and set up or improve your store.", link: "Know More" }, { num: "02", title: "Listing Optimization", text: "Optimize existing listings and create templates for new ones.", link: "Know More" }, { num: "03", title: "Media & Branding", text: "Professional photos and store branding.", link: "Know More" }, { num: "04", title: "Ongoing Management", text: "Regular optimization, new listings, and performance tracking.", link: "Know More" }] }
};
